### ISSUE TITLE
any chance using this in Web？

### ISSUE THREAD

**Issue by trim21** [scttcper/transmission#102]
At first, thanks for your work.

I'm writing a transmission Web ui and looking for a client sdk. But got is for nodejs runtime, have you consider support this in Web runtime？

**Comment by scttcper** [comment]
the new version might work in web depending on the bundler used

**Comment by scttcper** [comment]
I imagine there'd be cors errors and stuff though, might not parse cookies correctly

**Comment by vsnthdev** [comment]
So, I tried to use this package for a React app and turns out it doesn't work with Vite by default, I'm still trying to figure out how to get it to work.

Any clues on how to get it working?

**Comment by scttcper** [comment]
@vsnthdev seems fine to me https://stackblitz.com/edit/vitejs-vite-m3ovk4?file=src%2FApp.tsx
