### ISSUE TITLE
Browser will request loop login when using typescript

### ISSUE THREAD

**Issue by lanruqing** [scttcper/transmission#104]
Hi,
I want to using @ctrl/transmission in a react project that based on typescript, but the browser always popup a transmission server login dialog, and this will displayed in a loop after each login. In final it will get 401 error.
But when I using in a javascript react project, it will login automation.

In typescript:
![image](https://github.com/scttcper/transmission/assets/13705679/b7ae6ee7-33bd-4c59-85e6-c4ff9e1032ed)

Thanks for your attention!

**Comment by scttcper** [comment]
Haven't tried any of them directly inside the browser. I would assume this library doesn't work there

**Comment by lanruqing** [comment]
> Haven't tried any of them directly inside the browser. I would assume this library doesn't work there

thank you for reply😃
