### ISSUE TITLE
Feature request: Add `hash` to `NormalizedTorrent` 

### ISSUE THREAD

**Issue by FrancoisLef** [scttcper/transmission#93]
Hello there 👋

Do you think you can add a `hash` field to the `NormalizedTorrent` type?

The problem I am having with Transmission is that restarting the service causes the torrent IDs to change. 
The only unique data I have found is the `hashString` property.
It would be super cool to have it directly on the normalized data 🤌

Thanks !

**Comment by scttcper** [comment]
the id returned with NormalizedTorrent is the hash

**Comment by craigharman** [comment]
I am getting an integer 1, and not the hash string when I return the result of `normalizedAddTorrent`. Shouldn't this be the hash?

Line 218 of transmission.ts says `const torrentId = res.arguments['torrent-added'].id;` 
Shouldn't that be `const torrentId = res.arguments['torrent-added'].hashString;`

**Comment by scttcper** [comment]
yall were right. I've added it as `hash` as part of the normalized torrent data

**Comment by craigharman** [comment]
Thanks for doing this @scttcper. Will you be making a similar changes to the other torrent client projects? As currently they are inconsistent. eg. QBittorrent doesn't have a hash property, it stores the hash in the id property. Would assume that the normalized torrent should be the same throughout all projects?

**Comment by scttcper** [comment]
maybe... It might be better to do a major version and start using the hash as the id in transmission instead? It sounds like it should be possible to switch https://github.com/transmission/transmission/blob/main/extras/rpc-spec.txt#L109

**Comment by scttcper** [comment]
@craigharman let me know if https://github.com/scttcper/transmission/pull/98 makes sense

**Comment by craigharman** [comment]
Looks good @scttcper . This brings Transmission into line with [QBitTorrent](https://github.com/scttcper/qbittorrent) which also uses the hash as ID so is now consistent which is great.
